<a href="https://colab.research.google.com/github/juanpajedrez/pytorch_learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

if you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
!nvidia-smi-7

/bin/bash: line 1: nvidia-smi-7: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Take a look at what torch version you have
print(torch.__version__)

2.5.1+cu121


### Introduction to tensors
#### Creating tensors

Pytorch tensors are created using
`torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
# Lets find about dimenssions
scalar.ndim

0

In [5]:
#Lets get the items in tensor as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])

#Selecting matrices
print(matrix[0])
print(matrix[1])

tensor([7, 8])
tensor([ 9, 10])


In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
# Tensor
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
# Lets get the number of dimensions
Tensor.ndim

3

In [14]:
#Lets get the shape
Tensor.shape

torch.Size([1, 3, 3])

In [15]:
# So if we obtain the first element
print(Tensor[0])
print(Tensor[0].shape)

#OW, ok, and then if we select 1
print(Tensor[0, 0])
print(Tensor[0, 0].shape)
print(Tensor[0, 1])
print(Tensor[0, 1].shape)

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])
torch.Size([3, 3])
tensor([1, 2, 3])
torch.Size([3])
tensor([3, 6, 9])
torch.Size([3])


### Randomness in Pytorch Tensors

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -. update random numbers -> look at data -> update random numbers`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
### Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.7404, 0.1273, 0.5954, 0.1284],
        [0.8805, 0.4981, 0.2211, 0.7511],
        [0.1391, 0.3536, 0.9406, 0.2639]])


In [17]:
# Create a random tensor with similar shape to an image tensor
# sometimes colour channels come at the end, but can be in the beginning
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [18]:
torch.rand(size=(3, 3))

tensor([[0.2096, 0.5698, 0.3986],
        [0.4671, 0.7414, 0.3152],
        [0.4309, 0.7837, 0.6131]])

### Zeros and ones tensors

In [19]:
# Create a tensor of all zeros (a mask! :))
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Create a tensors of all ones

In [21]:
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
torch.__version__

'2.5.1+cu121'

In [25]:
### Creating tensors like (shape of one tensor -> defines new shape tensor)
print(one_to_ten.shape)

# Creating it
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

torch.Size([10])


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes

**Note** tensor datatypes is one of the 3 big issues and errors you will run into with Pytorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [26]:
# Float 32 tensor
test_dtypes_tensor = torch.tensor([3, 6.0, 9.0],
                                  dtype = None, #What datatype is the tensor (e.g: float32, float16)
                                  device = "cpu", #What device where the tensor lives in
                                  requires_grad=False) #weather to track gradients of wtih this tensors operations
test_dtypes_tensor

tensor([3., 6., 9.])

In [27]:
test_dtypes_tensor.dtype

torch.float32

In [28]:
test_dtypes_tensor = test_dtypes_tensor.type(torch.float16)
test_dtypes_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
int_32_tensor = torch.tensor([3, 6, 8], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 8])

In [30]:
test_dtypes_tensor * int_32_tensor

tensor([ 9., 36., 72.], dtype=torch.float16)

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, you can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, you can use `tensor.shape`.
3. Tensors not on the right device - to get device from a tensor, can use tensor.device `tensor.device`

In [31]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8667, 0.9092, 0.8105, 0.9131],
        [0.2266, 0.2537, 0.4577, 0.5191],
        [0.1471, 0.5324, 0.2997, 0.3601]])

In [32]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor {some_tensor.dtype}")
print(f"Shape of tensor {some_tensor.shape}")
print(f"Device of tensor {some_tensor.device}")

tensor([[0.8667, 0.9092, 0.8105, 0.9131],
        [0.2266, 0.2537, 0.4577, 0.5191],
        [0.1471, 0.5324, 0.2997, 0.3601]])
Datatype of tensor torch.float32
Shape of tensor torch.Size([3, 4])
Device of tensor cpu


### Manipulating Tensors (tensor operations).

Tensor Operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication.

In [33]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)

tensor([11, 12, 13])


In [34]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [35]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [36]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [37]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways to performing multiplication in neural networks and deep learning.

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two rules that performing matrix multiplication needs to satisfy.
1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` wont work.
* `(3, 2) @ (2, 3)` this will work.
* `(2, 3) @ (3, 2)` this will work.
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [38]:
#This will work
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6576, 0.9445],
        [0.2128, 0.6048]])

In [39]:
#This will work
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.0925, 0.0415, 0.3858],
        [0.0482, 0.0291, 0.5895],
        [0.7835, 0.2921, 0.2134]])

In [40]:
# Element wise multiplication
print(f"Tensor multiplication: {tensor * tensor}")

Tensor multiplication: tensor([1, 4, 9])


In [41]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [43]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.24 ms, sys: 0 ns, total: 1.24 ms
Wall time: 1.89 ms


In [44]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 27 µs, sys: 4 µs, total: 31 µs
Wall time: 33.6 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [45]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

#Perform matmul (perform an error; inner dimensions doesnt match)
#torch.matmul(tensor_A, tensor_B)

To fix out tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

**transpose** switches the axes or dimensions of a given tensor.


In [46]:
print(tensor_B.T)
print(tensor_B.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]])
torch.Size([2, 3])


In [47]:
print(tensor_B)
print(tensor_B.shape)

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])
torch.Size([3, 2])


In [48]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"News shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")


Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
News shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [49]:
#Create a tensor
x = torch.arange(0, 100, 10)
print(x)
print(x.dtype)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
torch.int64


In [50]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [51]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [52]:
#Find the mean (convert it to torch.float32 so it works)
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [53]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [54]:
#Lets find the index
print(x)

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])


In [55]:
# Find min index. position in tensor has the min value with argmin -> returns index position of target tensor min value
x.argmin()

tensor(0)

In [56]:
x[x.argmin()]

tensor(0)

In [57]:
#Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [58]:
x[x.argmax()]

tensor(90)

### Reshaping, stacking, squeezing, and unsqueezing tensors.

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - removes all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permutted (swapped) in a certain way.

In [59]:
# Lets create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [60]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [62]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor).
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [63]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], axis = 1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [64]:
# torch.squeeze() - removes all dimensions 1 from a target tensor.
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [65]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [66]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order.
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0-> 1, 1-> 2, 2-> 0

print(f"Previous shape: {x_original.shape}")
print(f"Permuted shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [67]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
#Lets take a look if the permuted value has changed!
print(f"Original value at position [0, 0, 0]: {x_original[0, 0, 0]}")
print(f"New permuted value at position [0, 0, 0]: {x_permuted[0, 0, 0]}")

Original value at position [0, 0, 0]: 0.8246322274208069
New permuted value at position [0, 0, 0]: 0.8246322274208069


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with Numpy.

In [70]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [71]:
# Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [72]:
# Lets index on the middle bracket (dim = 1)
print(x[0, 0])
print(x[0][0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [73]:
# Lets index on the most inner bracket (last dimension)
print(x[0][2][2])

tensor(9)


In [74]:
# You can also use the ":" to select "all of a target dimension"
x[:, 0]

tensor([[1, 2, 3]])

In [75]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [76]:
# Get all values of the 0th dimension but only the 1 index value of 1st and 2nd dim.
x[:, 1, 1]

tensor([5])

In [77]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [78]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [79]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`.
* Pytorch tensor -> NumPy -> `torch.Tensor.numpy()`.

In [80]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [81]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Tensor to NumPy array
tensor = torch.ones(7) # torch default type: torch.dtype.float32
numpy_tensor = tensor.numpy() # numpy default type: np.dtype.float64
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [83]:
# Change the tensor, what happens to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce the randomness in neural networks in PyTorch comes the concept of **random seed**.

Essentially, what the random seed does is "flavour" the randomness.

In [84]:
import torch

#Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6564, 0.2626, 0.5762, 0.7827],
        [0.2524, 0.9459, 0.2070, 0.8628],
        [0.2746, 0.9522, 0.5441, 0.9084]])
tensor([[0.2364, 0.5992, 0.5772, 0.2270],
        [0.5506, 0.1555, 0.1564, 0.6321],
        [0.6742, 0.8428, 0.4393, 0.1660]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [85]:
# Lets make some random but reproducible tensors
import torch

#Set the random seed (it only works for one block of code)
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# If you want to set them equal, you set them differently
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations).

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorcg working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well).
2. Use your own GPU - takes a little bit of a setup and requires the investment of purchasing a GPU that allows deep learning.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation. https://pytorch.org/get-started/locally/


In [87]:
!nvidia-smi

Mon Dec 30 01:38:35 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [89]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since its capalbe of running on the GPU or CPU, its best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html

E.g run on GPU if available, else default to CPU.

In [90]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [91]:
# Count the number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because results in faster calculations

In [92]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [93]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [94]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [96]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU.
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [97]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')